FROM cassandra

RUN apt-get update -yqq && apt-get -yqq upgrade && apt-get install -yqq wget

WORKDIR /app

RUN wget https://repo1.maven.org/maven2/io/debezium/debezium-connector-cassandra/1.1.0.Beta1/debezium-connector-cassandra-1.1.0.Beta1-jar-with-dependencies.jar

COPY default_cassandra.yaml /etc/cassandra/cassandra.yaml

RUN mkdir /etc/debezium
RUN mkdir -p /tmp/debezium/offsets
RUN mkdir -p /tmp/debezium/relocation
COPY default_config.properties /etc/debezium/cdc.properties

ADD start-debezium.sh start-debezium.sh

RUN chmod 777 start-debezium.sh
